# meta.yaml is configuration for the tool conda-build.
#
# meta.yaml reference:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
#
{% set name = "dask-gateway" %}
{% set version = "2023.1.1" %}



# Common configuration for dask-gateway and dask-gateway-server outputs
# -----------------------------------------------------------------------------
package:
  version: {{ version }}
  name: {{ name|lower }}

source:
  url: https://github.com/dask/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 921292f847f66413afdcd5aa06544ddf62ac0f293a1618f83264061e0e86e7dc

build:
  number: 0
  noarch: python



# Specific configuration for outputs beyond the common configuration above
# -----------------------------------------------------------------------------
outputs:
  # core package: server
  - name: dask-gateway-server
    build:
      # dask-gateway-server don't support windows, dask-gateway does
      #
      skip: true  # [target_platform == 'win-64']
      script: >-
        cd dask-gateway-server && python -m pip install . -vv --no-deps
      # entry_points below should match entry_points in setup.py:
      # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py
      #
      entry_points:
        - dask-gateway-server = dask_gateway_server.app:main
        - dask-gateway-jobqueue-launcher = dask_gateway_server.backends.jobqueue.launcher:main
    requirements:
      build:
        # This jinja function expands to go-nocgo_<target-platform>, and that
        # specific package will setup GOOS and GOARCH so that we compile for the
        # right target architecture.
        #
        # For details about compiler(), see
        # https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2.
        #
        - {{ compiler('go') }}
      host:
        - python >=3.8
        - pip
      run:
        - python
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/requirements.txt
        #
        - aiohttp
        - colorlog
        - cryptography
        - traitlets >=5.2.2.post1
    test:
      imports:
        - dask_gateway_server
      commands:
        - dask-gateway-server --help
        # FIXME: For some reason, "which dask-gateway-server" errors even though
        #        "dask-gateway-server --help" works in linux-aarch64
        #        specifically.
        #
        #        Due to this, we have disabled the test below specifically for
        #        linux-aarch64 but assume the package still is functional.
        #
        - which dask-gateway-jobqueue-launcher  # [target_platform != 'linux-aarch64']


  # core package: client
  - name: dask-gateway
    build:
      noarch: python
      script: >-
        cd dask-gateway && python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway/requirements.txt
        #
        - aiohttp
        - click
        - dask >=2022.4.0
        - distributed >=2022.4.0
        - pyyaml
        - tornado
    test:
      imports:
        - dask_gateway



  # client: kerberos authentication
  - name: dask-gateway-kerberos
    requirements:
      run:
        - dask-gateway {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway/setup.py#L207
        #
        - pykerberos  # [target_platform != 'win-64']
        - winkerberos  # [target_platform == 'win-64']
    test:
      imports:
        - dask_gateway

  # server: kerberos authentication
  - name: dask-gateway-server-kerberos
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py#L207
        #
        - pykerberos
    test:
      imports:
        - dask_gateway_server

  # server: local backend
  - name: dask-gateway-server-local
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py#L207
        #
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.local

  # server: jobqueue backends
  - name: dask-gateway-server-jobqueue
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py#L207
        #
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.jobqueue.slurm
        - dask_gateway_server.backends.jobqueue.pbs

  # server: hadoop yarn backend
  - name: dask-gateway-server-yarn
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py#L207
        #
        - sqlalchemy
        - skein >=0.7.3
    test:
      imports:
        - dask_gateway_server.backends.yarn

  # server: kubernetes backend
  - name: dask-gateway-server-kubernetes
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server {{ version }}
        # Requirements below should match content of setup.py's extras_require:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py#L207
        #
        - kubernetes_asyncio
    test:
      imports:
        - dask_gateway_server.backends.kubernetes




# Additional information
# -----------------------------------------------------------------------------

about:
  home: http://github.com/dask/dask-gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A multi-tenant server for securely deploying and managing Dask clusters.
  description: A multi-tenant server for securely deploying and managing Dask clusters.
  doc_url: https://gateway.dask.org
  dev_url: http://github.com/dask/dask-gateway

extra:
  # To add new maintainers, open an issue with a specific title as described in
  # https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list
  #
  recipe-maintainers:
    - consideRatio
    - jacobtomlinson
    - jcrist
    - martindurant
    - TomAugspurger
